export const THUMBNAIL_WIDTH = 1600;
export const THUMBNAIL_HEIGHT = 900;
export const RESOLUTION = THUMBNAIL_HEIGHT * THUMBNAIL_WIDTH;

export const NOISE_STRENGTH = [
  {
    TRIANGLE_SIZE: 30, // 가장 약하게
    TRIANGLE_GAP: 10,
    TRIANGLE_COUNT: (THUMBNAIL_WIDTH / 8) * (THUMBNAIL_HEIGHT / 8),
  },
  {
    TRIANGLE_SIZE: 40, // 약하게
    TRIANGLE_GAP: 12,
    TRIANGLE_COUNT: (THUMBNAIL_WIDTH / 10) * (THUMBNAIL_HEIGHT / 10),
  },
  {
    TRIANGLE_SIZE: 50, // 조금 약하게
    TRIANGLE_GAP: 16,
    TRIANGLE_COUNT: (THUMBNAIL_WIDTH / 12) * (THUMBNAIL_HEIGHT / 12),
  },
  {
    TRIANGLE_SIZE: 60, // 조금 강하게
    TRIANGLE_GAP: 20,
    TRIANGLE_COUNT: (THUMBNAIL_WIDTH / 16) * (THUMBNAIL_HEIGHT / 16),
  },
  {
    TRIANGLE_SIZE: 80, // 강하게
    TRIANGLE_GAP: 30,
    TRIANGLE_COUNT: (THUMBNAIL_WIDTH / 18) * (THUMBNAIL_HEIGHT / 18),
  },
  {
    TRIANGLE_SIZE: 150, // 가장 강하게
    TRIANGLE_GAP: 40,
    TRIANGLE_COUNT: (THUMBNAIL_WIDTH / 40) * (THUMBNAIL_HEIGHT / 40),
  },
];

export const RGBA_ARRAY_SIZE = 4;
export const MAX_NOISE_LEVEL = 6;
export const MIN_NOISE_LEVEL = 1;

export const ROTATE_DEGREE = 60;
