export const THUMBNAIL_WIDTH = 1600;
export const THUMBNAIL_HEIGHT = 900;

export const TRIANGLE_WIDTH = 14;
export const TRIANGLE_GAP = 5;

export const TRIANGLE_COUNT =
  (THUMBNAIL_WIDTH / TRIANGLE_WIDTH) * (THUMBNAIL_HEIGHT / TRIANGLE_WIDTH) * 10;

export const RGBA_ARRAY_SIZE = 4;
